### ISSUE TITLE
Olabs Widget plugins

### ISSUE THREAD

**Issue by chrisvidal** [lokios/octobererp#5]
### Expected behavior
not sure

### Actual behavior
this php code appears as text just above the widget that I added in the dashboard.

```php
property('customWidget') != "" ? $this->property('customWidget') : 0; $custom_widget_modal = Olabs\Widgets\Models\ReportWidget::where('id', $custom_widget)->first(); if($custom_widget_modal) { eval("?>".$custom_widget_modal->content."
```

### Steps to reproduce the behavior
1. creating a new widget, insert 'Hello Wolrd' in the content
2. add the widget in the dashboard

**Comment by amit-srivastava** [comment]
Issue Fixed.
